=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Komoju
  class CreateRefundRequestRequest < ApiModelBase
    # The payment amount before tax, greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
    attr_accessor :amount

    # Customer's name in half-width katakana, as registered at the bank.
    attr_accessor :customer_name

    # Name of the customer's bank.
    attr_accessor :bank_name

    # Optional 4-digit Zengin bank code.
    attr_accessor :bank_code

    # Name of the customer's bank branch.
    attr_accessor :branch_name

    # 3-digit branch number.
    attr_accessor :branch_number

    # Type of the customer's bank account.
    attr_accessor :account_type

    # 7-digit bank account number to deposit the refund into.
    attr_accessor :account_number

    # Whether the refund should include the original payment method fee.
    attr_accessor :include_payment_method_fee

    # Optional description or reason for this refund request.
    attr_accessor :description

    attr_accessor :platform_details

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'amount' => :'amount',
        :'customer_name' => :'customer_name',
        :'bank_name' => :'bank_name',
        :'bank_code' => :'bank_code',
        :'branch_name' => :'branch_name',
        :'branch_number' => :'branch_number',
        :'account_type' => :'account_type',
        :'account_number' => :'account_number',
        :'include_payment_method_fee' => :'include_payment_method_fee',
        :'description' => :'description',
        :'platform_details' => :'platform_details'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'amount' => :'Integer',
        :'customer_name' => :'String',
        :'bank_name' => :'String',
        :'bank_code' => :'String',
        :'branch_name' => :'String',
        :'branch_number' => :'String',
        :'account_type' => :'String',
        :'account_number' => :'Integer',
        :'include_payment_method_fee' => :'Boolean',
        :'description' => :'String',
        :'platform_details' => :'PlatformDetails'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Komoju::CreateRefundRequestRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Komoju::CreateRefundRequestRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'customer_name')
        self.customer_name = attributes[:'customer_name']
      else
        self.customer_name = nil
      end

      if attributes.key?(:'bank_name')
        self.bank_name = attributes[:'bank_name']
      else
        self.bank_name = nil
      end

      if attributes.key?(:'bank_code')
        self.bank_code = attributes[:'bank_code']
      end

      if attributes.key?(:'branch_name')
        self.branch_name = attributes[:'branch_name']
      end

      if attributes.key?(:'branch_number')
        self.branch_number = attributes[:'branch_number']
      else
        self.branch_number = nil
      end

      if attributes.key?(:'account_type')
        self.account_type = attributes[:'account_type']
      else
        self.account_type = nil
      end

      if attributes.key?(:'account_number')
        self.account_number = attributes[:'account_number']
      else
        self.account_number = nil
      end

      if attributes.key?(:'include_payment_method_fee')
        self.include_payment_method_fee = attributes[:'include_payment_method_fee']
      else
        self.include_payment_method_fee = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'platform_details')
        self.platform_details = attributes[:'platform_details']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @amount < 0
        invalid_properties.push('invalid value for "amount", must be greater than or equal to 0.')
      end

      if @customer_name.nil?
        invalid_properties.push('invalid value for "customer_name", customer_name cannot be nil.')
      end

      if @bank_name.nil?
        invalid_properties.push('invalid value for "bank_name", bank_name cannot be nil.')
      end

      if @branch_number.nil?
        invalid_properties.push('invalid value for "branch_number", branch_number cannot be nil.')
      end

      if @account_type.nil?
        invalid_properties.push('invalid value for "account_type", account_type cannot be nil.')
      end

      if @account_number.nil?
        invalid_properties.push('invalid value for "account_number", account_number cannot be nil.')
      end

      if @include_payment_method_fee.nil?
        invalid_properties.push('invalid value for "include_payment_method_fee", include_payment_method_fee cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @amount.nil?
      return false if @amount < 0
      return false if @customer_name.nil?
      return false if @bank_name.nil?
      return false if @branch_number.nil?
      return false if @account_type.nil?
      account_type_validator = EnumAttributeValidator.new('String', ["normal", "checking", "savings"])
      return false unless account_type_validator.valid?(@account_type)
      return false if @account_number.nil?
      return false if @include_payment_method_fee.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      if amount < 0
        fail ArgumentError, 'invalid value for "amount", must be greater than or equal to 0.'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_name Value to be assigned
    def customer_name=(customer_name)
      if customer_name.nil?
        fail ArgumentError, 'customer_name cannot be nil'
      end

      @customer_name = customer_name
    end

    # Custom attribute writer method with validation
    # @param [Object] bank_name Value to be assigned
    def bank_name=(bank_name)
      if bank_name.nil?
        fail ArgumentError, 'bank_name cannot be nil'
      end

      @bank_name = bank_name
    end

    # Custom attribute writer method with validation
    # @param [Object] branch_number Value to be assigned
    def branch_number=(branch_number)
      if branch_number.nil?
        fail ArgumentError, 'branch_number cannot be nil'
      end

      @branch_number = branch_number
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] account_type Object to be assigned
    def account_type=(account_type)
      validator = EnumAttributeValidator.new('String', ["normal", "checking", "savings"])
      unless validator.valid?(account_type)
        fail ArgumentError, "invalid value for \"account_type\", must be one of #{validator.allowable_values}."
      end
      @account_type = account_type
    end

    # Custom attribute writer method with validation
    # @param [Object] account_number Value to be assigned
    def account_number=(account_number)
      if account_number.nil?
        fail ArgumentError, 'account_number cannot be nil'
      end

      @account_number = account_number
    end

    # Custom attribute writer method with validation
    # @param [Object] include_payment_method_fee Value to be assigned
    def include_payment_method_fee=(include_payment_method_fee)
      if include_payment_method_fee.nil?
        fail ArgumentError, 'include_payment_method_fee cannot be nil'
      end

      @include_payment_method_fee = include_payment_method_fee
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          amount == o.amount &&
          customer_name == o.customer_name &&
          bank_name == o.bank_name &&
          bank_code == o.bank_code &&
          branch_name == o.branch_name &&
          branch_number == o.branch_number &&
          account_type == o.account_type &&
          account_number == o.account_number &&
          include_payment_method_fee == o.include_payment_method_fee &&
          description == o.description &&
          platform_details == o.platform_details
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [amount, customer_name, bank_name, bank_code, branch_name, branch_number, account_type, account_number, include_payment_method_fee, description, platform_details].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      begin
        new(transformed_hash)
      rescue ArgumentError => e
        obj = allocate
        transformed_hash.each { |k, v| obj.instance_variable_set(:"@#{k}", v) }
        obj
      end
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value) rescue value
      when :Date
        Date.parse(value) rescue value
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Komoju.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
