=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Komoju
  class Currency
    JPY = "JPY".freeze
    USD = "USD".freeze
    EUR = "EUR".freeze
    TWD = "TWD".freeze
    KRW = "KRW".freeze
    PLN = "PLN".freeze
    GBP = "GBP".freeze
    HKD = "HKD".freeze
    SGD = "SGD".freeze
    NZD = "NZD".freeze
    AUD = "AUD".freeze
    IDR = "IDR".freeze
    MYR = "MYR".freeze
    PHP = "PHP".freeze
    THB = "THB".freeze
    CNY = "CNY".freeze
    BRL = "BRL".freeze
    CHF = "CHF".freeze
    CAD = "CAD".freeze
    VND = "VND".freeze

    def self.all_vars
      @all_vars ||= [JPY, USD, EUR, TWD, KRW, PLN, GBP, HKD, SGD, NZD, AUD, IDR, MYR, PHP, THB, CNY, BRL, CHF, CAD, VND].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      value
    end
  end
end
