=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Komoju
  class Installments
    N3 = "3".freeze
    N5 = "5".freeze
    N6 = "6".freeze
    N10 = "10".freeze
    N12 = "12".freeze
    N15 = "15".freeze
    N18 = "18".freeze
    N20 = "20".freeze
    N24 = "24".freeze
    REVOLVING = "revolving".freeze

    def self.all_vars
      @all_vars ||= [N3, N5, N6, N10, N12, N15, N18, N20, N24, REVOLVING].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      value
    end
  end
end
