=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Komoju
  # Specify payment type and additional attributes required for each payment type.
  module PaymentDetailsAll
    class << self
      # List of class defined in oneOf (OpenAPI v3)
      def openapi_one_of
        [
          :'PaymentDetailsAU',
          :'PaymentDetailsAlipay',
          :'PaymentDetailsAlipayHK',
          :'PaymentDetailsAupay',
          :'PaymentDetailsBancontact',
          :'PaymentDetailsBankTransfer',
          :'PaymentDetailsBitCash',
          :'PaymentDetailsBlik',
          :'PaymentDetailsCVS',
          :'PaymentDetailsCreditCard',
          :'PaymentDetailsCreditCardBrazil',
          :'PaymentDetailsCreditCardKorea',
          :'PaymentDetailsCreditCardTerminal',
          :'PaymentDetailsCultureVoucher',
          :'PaymentDetailsDana',
          :'PaymentDetailsDocomo',
          :'PaymentDetailsDokuWallet',
          :'PaymentDetailsDospara',
          :'PaymentDetailsDragonpay',
          :'PaymentDetailsEnets',
          :'PaymentDetailsEpospay',
          :'PaymentDetailsEps',
          :'PaymentDetailsFpx',
          :'PaymentDetailsGCash',
          :'PaymentDetailsGiropay',
          :'PaymentDetailsHappyMoney',
          :'PaymentDetailsIdeal',
          :'PaymentDetailsKakaopay',
          :'PaymentDetailsKonbini',
          :'PaymentDetailsMerpay',
          :'PaymentDetailsMobile',
          :'PaymentDetailsMobileJapan',
          :'PaymentDetailsMultibanco',
          :'PaymentDetailsMybank',
          :'PaymentDetailsNarvesen',
          :'PaymentDetailsNaverpay',
          :'PaymentDetailsNetCash',
          :'PaymentDetailsOvo',
          :'PaymentDetailsPaidy',
          :'PaymentDetailsPayEasy',
          :'PaymentDetailsPayPay',
          :'PaymentDetailsPayco',
          :'PaymentDetailsPaypost',
          :'PaymentDetailsPaysafeCard',
          :'PaymentDetailsPaysafeCash',
          :'PaymentDetailsPaysera',
          :'PaymentDetailsPayu',
          :'PaymentDetailsPerlas',
          :'PaymentDetailsPix',
          :'PaymentDetailsPoli',
          :'PaymentDetailsPrzelewy24',
          :'PaymentDetailsRakutenpay',
          :'PaymentDetailsSepaTransfer',
          :'PaymentDetailsSofortbanking',
          :'PaymentDetailsSoftbank',
          :'PaymentDetailsTNG',
          :'PaymentDetailsToss',
          :'PaymentDetailsTruemoney',
          :'PaymentDetailsUnionpay',
          :'PaymentDetailsWebMoney',
          :'PaymentDetailsWechatpay'
        ]
      end

      # Discriminator's property name (OpenAPI v3)
      def openapi_discriminator_name
        :'type'
      end

      # Discriminator's mapping (OpenAPI v3)
      def openapi_discriminator_mapping
        {
          :'alipay' => :'PaymentDetailsAlipay',
          :'alipay_hk' => :'PaymentDetailsAlipayHK',
          :'au' => :'PaymentDetailsAU',
          :'aupay' => :'PaymentDetailsAupay',
          :'bancontact' => :'PaymentDetailsBancontact',
          :'bank_transfer' => :'PaymentDetailsBankTransfer',
          :'bit_cash' => :'PaymentDetailsBitCash',
          :'blik' => :'PaymentDetailsBlik',
          :'credit_card' => :'PaymentDetailsCreditCard',
          :'credit_card_brazil' => :'PaymentDetailsCreditCardBrazil',
          :'credit_card_korea' => :'PaymentDetailsCreditCardKorea',
          :'credit_card_terminal' => :'PaymentDetailsCreditCardTerminal',
          :'culture_voucher' => :'PaymentDetailsCultureVoucher',
          :'cvs' => :'PaymentDetailsCVS',
          :'dana' => :'PaymentDetailsDana',
          :'docomo' => :'PaymentDetailsDocomo',
          :'doku_wallet' => :'PaymentDetailsDokuWallet',
          :'dospara' => :'PaymentDetailsDospara',
          :'dragonpay' => :'PaymentDetailsDragonpay',
          :'enets' => :'PaymentDetailsEnets',
          :'epospay' => :'PaymentDetailsEpospay',
          :'eps' => :'PaymentDetailsEps',
          :'fpx' => :'PaymentDetailsFpx',
          :'gcash' => :'PaymentDetailsGCash',
          :'giropay' => :'PaymentDetailsGiropay',
          :'happy_money' => :'PaymentDetailsHappyMoney',
          :'ideal' => :'PaymentDetailsIdeal',
          :'japan_mobile' => :'PaymentDetailsMobileJapan',
          :'kakaopay' => :'PaymentDetailsKakaopay',
          :'konbini' => :'PaymentDetailsKonbini',
          :'merpay' => :'PaymentDetailsMerpay',
          :'mobile' => :'PaymentDetailsMobile',
          :'multibanco' => :'PaymentDetailsMultibanco',
          :'mybank' => :'PaymentDetailsMybank',
          :'narvesen' => :'PaymentDetailsNarvesen',
          :'naverpay' => :'PaymentDetailsNaverpay',
          :'net_cash' => :'PaymentDetailsNetCash',
          :'ovo' => :'PaymentDetailsOvo',
          :'paidy' => :'PaymentDetailsPaidy',
          :'pay_easy' => :'PaymentDetailsPayEasy',
          :'payco' => :'PaymentDetailsPayco',
          :'paypay' => :'PaymentDetailsPayPay',
          :'paypost' => :'PaymentDetailsPaypost',
          :'paysafe_card' => :'PaymentDetailsPaysafeCard',
          :'paysafe_cash' => :'PaymentDetailsPaysafeCash',
          :'paysera' => :'PaymentDetailsPaysera',
          :'payu' => :'PaymentDetailsPayu',
          :'perlas' => :'PaymentDetailsPerlas',
          :'pix' => :'PaymentDetailsPix',
          :'poli' => :'PaymentDetailsPoli',
          :'przelewy24' => :'PaymentDetailsPrzelewy24',
          :'rakutenpay' => :'PaymentDetailsRakutenpay',
          :'sepa_transfer' => :'PaymentDetailsSepaTransfer',
          :'sofortbanking' => :'PaymentDetailsSofortbanking',
          :'softbank' => :'PaymentDetailsSoftbank',
          :'tng' => :'PaymentDetailsTNG',
          :'toss' => :'PaymentDetailsToss',
          :'truemoney' => :'PaymentDetailsTruemoney',
          :'unionpay' => :'PaymentDetailsUnionpay',
          :'web_money' => :'PaymentDetailsWebMoney',
          :'wechatpay' => :'PaymentDetailsWechatpay'
        }
      end

      # Builds the object
      # @param [Mixed] Data to be matched against the list of oneOf items
      # @return [Object] Returns the model or the data itself
      def build(data)
        discriminator_value = data[openapi_discriminator_name]
        return nil if discriminator_value.nil?

        klass = openapi_discriminator_mapping[discriminator_value.to_s.to_sym]
        return nil unless klass

        Komoju.const_get(klass).build_from_hash(data)
      end
    end
  end

end
