=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Komoju
  class PaymentMethod
    # Machine-readable type slug for this payment method (e.g. \"credit_card\", \"konbini\").
    attr_accessor :type

    # Hashed identifier of the payment gateway processing this method.
    attr_accessor :hashed_gateway

    # Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
    attr_accessor :amount

    attr_accessor :currency

    # Exchange rate applied when this payment method's currency differs from the session currency.
    attr_accessor :exchange_rate

    # Whether this payment method redirects the customer to an external site to complete payment.
    attr_accessor :offsite

    # Names of additional input fields required to complete payment with this method.
    attr_accessor :additional_fields

    attr_accessor :brands

    # Only for Konbini
    attr_accessor :seven_eleven_merchant_number

    # Only for Komoju Pay
    attr_accessor :installments

    # Only for Komoju Pay
    attr_accessor :api_endpoint

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'hashed_gateway' => :'hashed_gateway',
        :'amount' => :'amount',
        :'currency' => :'currency',
        :'exchange_rate' => :'exchange_rate',
        :'offsite' => :'offsite',
        :'additional_fields' => :'additional_fields',
        :'brands' => :'brands',
        :'seven_eleven_merchant_number' => :'seven_eleven_merchant_number',
        :'installments' => :'installments',
        :'api_endpoint' => :'api_endpoint'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'String',
        :'hashed_gateway' => :'String',
        :'amount' => :'Integer',
        :'currency' => :'Currency',
        :'exchange_rate' => :'Float',
        :'offsite' => :'Boolean',
        :'additional_fields' => :'Array<String>',
        :'brands' => :'PaymentMethodBrands',
        :'seven_eleven_merchant_number' => :'String',
        :'installments' => :'Array<PaymentMethodInstallmentsInner>',
        :'api_endpoint' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'seven_eleven_merchant_number',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Komoju::PaymentMethod` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Komoju::PaymentMethod`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'hashed_gateway')
        self.hashed_gateway = attributes[:'hashed_gateway']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'exchange_rate')
        self.exchange_rate = attributes[:'exchange_rate']
      end

      if attributes.key?(:'offsite')
        self.offsite = attributes[:'offsite']
      end

      if attributes.key?(:'additional_fields')
        if (value = attributes[:'additional_fields']).is_a?(Array)
          self.additional_fields = value
        end
      end

      if attributes.key?(:'brands')
        self.brands = attributes[:'brands']
      end

      if attributes.key?(:'seven_eleven_merchant_number')
        self.seven_eleven_merchant_number = attributes[:'seven_eleven_merchant_number']
      end

      if attributes.key?(:'installments')
        if (value = attributes[:'installments']).is_a?(Array)
          self.installments = value
        end
      end

      if attributes.key?(:'api_endpoint')
        self.api_endpoint = attributes[:'api_endpoint']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if !@amount.nil? && @amount < 0
        invalid_properties.push('invalid value for "amount", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type.nil?
      return false if !@amount.nil? && @amount < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      if amount < 0
        fail ArgumentError, 'invalid value for "amount", must be greater than or equal to 0.'
      end

      @amount = amount
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          hashed_gateway == o.hashed_gateway &&
          amount == o.amount &&
          currency == o.currency &&
          exchange_rate == o.exchange_rate &&
          offsite == o.offsite &&
          additional_fields == o.additional_fields &&
          brands == o.brands &&
          seven_eleven_merchant_number == o.seven_eleven_merchant_number &&
          installments == o.installments &&
          api_endpoint == o.api_endpoint
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, hashed_gateway, amount, currency, exchange_rate, offsite, additional_fields, brands, seven_eleven_merchant_number, installments, api_endpoint].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      begin
        new(transformed_hash)
      rescue ArgumentError => e
        obj = allocate
        transformed_hash.each { |k, v| obj.instance_variable_set(:"@#{k}", v) }
        obj
      end
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value) rescue value
      when :Date
        Date.parse(value) rescue value
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Komoju.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
