=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Komoju
  class Session
    # A unique 25-character alphanumeric resource identifier.
    attr_accessor :id

    # Resource type name, always \"session\".
    attr_accessor :resource

    attr_accessor :mode

    # Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
    attr_accessor :amount

    attr_accessor :currency

    # URL to redirect the customer to for completing the session.
    attr_accessor :session_url

    # URL the customer is redirected to after completing or cancelling the session.
    attr_accessor :return_url

    attr_accessor :default_locale

    # List of payment methods available for this session.
    attr_accessor :payment_methods

    # Timestamp when the session was created.
    attr_accessor :created_at

    # Timestamp when the session was cancelled, or null if not cancelled.
    attr_accessor :cancelled_at

    # Timestamp when the session was completed, or null if not completed.
    attr_accessor :completed_at

    attr_accessor :status

    # Whether the session has expired.
    attr_accessor :expired

    attr_accessor :merchant

    # Arbitrary key-value metadata attached to this session at creation time.
    attr_accessor :metadata

    attr_accessor :payment

    attr_accessor :payment_data

    # Subscription customer UUID. Only present when mode includes \"customer\".
    attr_accessor :customer_id

    attr_accessor :secure_token

    # Line items for this session. Only present when line items were provided on create.
    attr_accessor :line_items

    # Merchant UUID. Only present for Platform Model seller merchants.
    attr_accessor :merchant_id

    # Customer email. Only present when an email was provided.
    attr_accessor :email

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'resource' => :'resource',
        :'mode' => :'mode',
        :'amount' => :'amount',
        :'currency' => :'currency',
        :'session_url' => :'session_url',
        :'return_url' => :'return_url',
        :'default_locale' => :'default_locale',
        :'payment_methods' => :'payment_methods',
        :'created_at' => :'created_at',
        :'cancelled_at' => :'cancelled_at',
        :'completed_at' => :'completed_at',
        :'status' => :'status',
        :'expired' => :'expired',
        :'merchant' => :'merchant',
        :'metadata' => :'metadata',
        :'payment' => :'payment',
        :'payment_data' => :'payment_data',
        :'customer_id' => :'customer_id',
        :'secure_token' => :'secure_token',
        :'line_items' => :'line_items',
        :'merchant_id' => :'merchant_id',
        :'email' => :'email'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'resource' => :'String',
        :'mode' => :'SessionMode',
        :'amount' => :'Integer',
        :'currency' => :'Currency',
        :'session_url' => :'String',
        :'return_url' => :'String',
        :'default_locale' => :'Locale',
        :'payment_methods' => :'Array<PaymentMethod>',
        :'created_at' => :'Time',
        :'cancelled_at' => :'Time',
        :'completed_at' => :'Time',
        :'status' => :'SessionStatus',
        :'expired' => :'Boolean',
        :'merchant' => :'MerchantData',
        :'metadata' => :'Object',
        :'payment' => :'Payment',
        :'payment_data' => :'PaymentData',
        :'customer_id' => :'String',
        :'secure_token' => :'SecureToken',
        :'line_items' => :'Array<LineItem>',
        :'merchant_id' => :'String',
        :'email' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'return_url',
        :'cancelled_at',
        :'completed_at',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Komoju::Session` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Komoju::Session`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'resource')
        self.resource = attributes[:'resource']
      else
        self.resource = nil
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      else
        self.mode = nil
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'session_url')
        self.session_url = attributes[:'session_url']
      else
        self.session_url = nil
      end

      if attributes.key?(:'return_url')
        self.return_url = attributes[:'return_url']
      else
        self.return_url = nil
      end

      if attributes.key?(:'default_locale')
        self.default_locale = attributes[:'default_locale']
      else
        self.default_locale = nil
      end

      if attributes.key?(:'payment_methods')
        if (value = attributes[:'payment_methods']).is_a?(Array)
          self.payment_methods = value
        end
      else
        self.payment_methods = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'cancelled_at')
        self.cancelled_at = attributes[:'cancelled_at']
      else
        self.cancelled_at = nil
      end

      if attributes.key?(:'completed_at')
        self.completed_at = attributes[:'completed_at']
      else
        self.completed_at = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'expired')
        self.expired = attributes[:'expired']
      else
        self.expired = nil
      end

      if attributes.key?(:'merchant')
        self.merchant = attributes[:'merchant']
      else
        self.merchant = nil
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      else
        self.metadata = nil
      end

      if attributes.key?(:'payment')
        self.payment = attributes[:'payment']
      end

      if attributes.key?(:'payment_data')
        self.payment_data = attributes[:'payment_data']
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'secure_token')
        self.secure_token = attributes[:'secure_token']
      end

      if attributes.key?(:'line_items')
        if (value = attributes[:'line_items']).is_a?(Array)
          self.line_items = value
        end
      end

      if attributes.key?(:'merchant_id')
        self.merchant_id = attributes[:'merchant_id']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @id.to_s.length > 25
        invalid_properties.push('invalid value for "id", the character length must be smaller than or equal to 25.')
      end

      if @id.to_s.length < 25
        invalid_properties.push('invalid value for "id", the character length must be great than or equal to 25.')
      end

      if @resource.nil?
        invalid_properties.push('invalid value for "resource", resource cannot be nil.')
      end

      if @mode.nil?
        invalid_properties.push('invalid value for "mode", mode cannot be nil.')
      end

      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @amount < 0
        invalid_properties.push('invalid value for "amount", must be greater than or equal to 0.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @session_url.nil?
        invalid_properties.push('invalid value for "session_url", session_url cannot be nil.')
      end

      if @default_locale.nil?
        invalid_properties.push('invalid value for "default_locale", default_locale cannot be nil.')
      end

      if @payment_methods.nil?
        invalid_properties.push('invalid value for "payment_methods", payment_methods cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @expired.nil?
        invalid_properties.push('invalid value for "expired", expired cannot be nil.')
      end

      if @merchant.nil?
        invalid_properties.push('invalid value for "merchant", merchant cannot be nil.')
      end

      if @metadata.nil?
        invalid_properties.push('invalid value for "metadata", metadata cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @id.to_s.length > 25
      return false if @id.to_s.length < 25
      return false if @resource.nil?
      resource_validator = EnumAttributeValidator.new('String', ["session"])
      return false unless resource_validator.valid?(@resource)
      return false if @mode.nil?
      return false if @amount.nil?
      return false if @amount < 0
      return false if @currency.nil?
      return false if @session_url.nil?
      return false if @default_locale.nil?
      return false if @payment_methods.nil?
      return false if @created_at.nil?
      return false if @status.nil?
      return false if @expired.nil?
      return false if @merchant.nil?
      return false if @metadata.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      if id.to_s.length > 25
        fail ArgumentError, 'invalid value for "id", the character length must be smaller than or equal to 25.'
      end

      if id.to_s.length < 25
        fail ArgumentError, 'invalid value for "id", the character length must be great than or equal to 25.'
      end

      @id = id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] resource Object to be assigned
    def resource=(resource)
      validator = EnumAttributeValidator.new('String', ["session"])
      unless validator.valid?(resource)
        fail ArgumentError, "invalid value for \"resource\", must be one of #{validator.allowable_values}."
      end
      @resource = resource
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      if amount < 0
        fail ArgumentError, 'invalid value for "amount", must be greater than or equal to 0.'
      end

      @amount = amount
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          resource == o.resource &&
          mode == o.mode &&
          amount == o.amount &&
          currency == o.currency &&
          session_url == o.session_url &&
          return_url == o.return_url &&
          default_locale == o.default_locale &&
          payment_methods == o.payment_methods &&
          created_at == o.created_at &&
          cancelled_at == o.cancelled_at &&
          completed_at == o.completed_at &&
          status == o.status &&
          expired == o.expired &&
          merchant == o.merchant &&
          metadata == o.metadata &&
          payment == o.payment &&
          payment_data == o.payment_data &&
          customer_id == o.customer_id &&
          secure_token == o.secure_token &&
          line_items == o.line_items &&
          merchant_id == o.merchant_id &&
          email == o.email
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, resource, mode, amount, currency, session_url, return_url, default_locale, payment_methods, created_at, cancelled_at, completed_at, status, expired, merchant, metadata, payment, payment_data, customer_id, secure_token, line_items, merchant_id, email].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      begin
        new(transformed_hash)
      rescue ArgumentError => e
        obj = allocate
        transformed_hash.each { |k, v| obj.instance_variable_set(:"@#{k}", v) }
        obj
      end
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value) rescue value
      when :Date
        Date.parse(value) rescue value
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Komoju.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
