=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Komoju
  class SubmittedField < ApiModelBase
    # The input type for this field (e.g. \"text\", \"file\", \"boolean\").
    attr_accessor :field_type

    # Machine-readable key name of the field.
    attr_accessor :field

    # Human-readable display name of the field.
    attr_accessor :field_name

    attr_accessor :field_properties

    # Display order position of this field in the application form.
    attr_accessor :position

    # Whether this field is optional (true) or required (false).
    attr_accessor :optional

    attr_accessor :value

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'field_type' => :'field_type',
        :'field' => :'field',
        :'field_name' => :'field_name',
        :'field_properties' => :'field_properties',
        :'position' => :'position',
        :'optional' => :'optional',
        :'value' => :'value'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'field_type' => :'String',
        :'field' => :'String',
        :'field_name' => :'String',
        :'field_properties' => :'FieldFieldProperties',
        :'position' => :'Integer',
        :'optional' => :'Boolean',
        :'value' => :'SubmittedFieldAllOfValue'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'Field'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Komoju::SubmittedField` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Komoju::SubmittedField`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'field_type')
        self.field_type = attributes[:'field_type']
      else
        self.field_type = nil
      end

      if attributes.key?(:'field')
        self.field = attributes[:'field']
      else
        self.field = nil
      end

      if attributes.key?(:'field_name')
        self.field_name = attributes[:'field_name']
      else
        self.field_name = nil
      end

      if attributes.key?(:'field_properties')
        self.field_properties = attributes[:'field_properties']
      else
        self.field_properties = nil
      end

      if attributes.key?(:'position')
        self.position = attributes[:'position']
      else
        self.position = nil
      end

      if attributes.key?(:'optional')
        self.optional = attributes[:'optional']
      else
        self.optional = nil
      end

      if attributes.key?(:'value')
        self.value = attributes[:'value']
      else
        self.value = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @field_type.nil?
        invalid_properties.push('invalid value for "field_type", field_type cannot be nil.')
      end

      if @field.nil?
        invalid_properties.push('invalid value for "field", field cannot be nil.')
      end

      if @field_name.nil?
        invalid_properties.push('invalid value for "field_name", field_name cannot be nil.')
      end

      if @field_properties.nil?
        invalid_properties.push('invalid value for "field_properties", field_properties cannot be nil.')
      end

      if @position.nil?
        invalid_properties.push('invalid value for "position", position cannot be nil.')
      end

      if @optional.nil?
        invalid_properties.push('invalid value for "optional", optional cannot be nil.')
      end

      if @value.nil?
        invalid_properties.push('invalid value for "value", value cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @field_type.nil?
      return false if @field.nil?
      return false if @field_name.nil?
      return false if @field_properties.nil?
      return false if @position.nil?
      return false if @optional.nil?
      return false if @value.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] field_type Value to be assigned
    def field_type=(field_type)
      if field_type.nil?
        fail ArgumentError, 'field_type cannot be nil'
      end

      @field_type = field_type
    end

    # Custom attribute writer method with validation
    # @param [Object] field Value to be assigned
    def field=(field)
      if field.nil?
        fail ArgumentError, 'field cannot be nil'
      end

      @field = field
    end

    # Custom attribute writer method with validation
    # @param [Object] field_name Value to be assigned
    def field_name=(field_name)
      if field_name.nil?
        fail ArgumentError, 'field_name cannot be nil'
      end

      @field_name = field_name
    end

    # Custom attribute writer method with validation
    # @param [Object] field_properties Value to be assigned
    def field_properties=(field_properties)
      if field_properties.nil?
        fail ArgumentError, 'field_properties cannot be nil'
      end

      @field_properties = field_properties
    end

    # Custom attribute writer method with validation
    # @param [Object] position Value to be assigned
    def position=(position)
      if position.nil?
        fail ArgumentError, 'position cannot be nil'
      end

      @position = position
    end

    # Custom attribute writer method with validation
    # @param [Object] optional Value to be assigned
    def optional=(optional)
      if optional.nil?
        fail ArgumentError, 'optional cannot be nil'
      end

      @optional = optional
    end

    # Custom attribute writer method with validation
    # @param [Object] value Value to be assigned
    def value=(value)
      if value.nil?
        fail ArgumentError, 'value cannot be nil'
      end

      @value = value
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          field_type == o.field_type &&
          field == o.field &&
          field_name == o.field_name &&
          field_properties == o.field_properties &&
          position == o.position &&
          optional == o.optional &&
          value == o.value
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [field_type, field, field_name, field_properties, position, optional, value].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      begin
        new(transformed_hash)
      rescue ArgumentError => e
        obj = allocate
        transformed_hash.each { |k, v| obj.instance_variable_set(:"@#{k}", v) }
        obj
      end
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value) rescue value
      when :Date
        Date.parse(value) rescue value
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Komoju.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
