# -*- encoding: utf-8 -*-

=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "komoju-sdk/version"

Gem::Specification.new do |s|
  s.name        = "komoju-sdk"
  s.version     = Komoju::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["KOMOJU Co., Ltd."]
  s.email       = [""]
  s.homepage    = "https://github.com/komoju/komoju-ruby-sdk"
  s.summary     = "KOMOJU API Ruby Gem"
  s.description = "Full featured access to the KOMOJU payments system."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'faraday', '>= 2.14.2', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart', '~> 1.0'
  s.add_runtime_dependency 'marcel', '~> 1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
