=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Komoju::SessionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SessionsApi' do
  before do
    # run before each test
    @api_instance = Komoju::SessionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SessionsApi' do
    it 'should create an instance of SessionsApi' do
      expect(@api_instance).to be_instance_of(Komoju::SessionsApi)
    end
  end

  # unit tests for cancel_session
  # Session: Cancel
  # Cancels a session.
  # @param id A unique identifier for the session.
  # @param [Hash] opts the optional parameters
  # @return [Session]
  describe 'cancel_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_session
  # Session: Create
  # Creates a session.
  # @param create_session_request 
  # @param [Hash] opts the optional parameters
  # @return [Session]
  describe 'create_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pay_session
  # Session: Pay
  # Provide customer payment details to pay for a session.
  # @param id A unique identifier for the session.
  # @param pay_session_request 
  # @param [Hash] opts the optional parameters
  # @return [PaySessionResponse]
  describe 'pay_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_session
  # Session: Show
  # Retrieves a Session given its ID.  A Session&#39;s status changes when the user completes or cancels their payment. You can listen for those events via webhooks, or use this API to poll for changes.
  # @param id A unique identifier for the session.
  # @param [Hash] opts the optional parameters
  # @return [Session]
  describe 'show_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
