=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Komoju::ChargebackDefense
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Komoju::ChargebackDefense do
  #let(:instance) { Komoju::ChargebackDefense.new }

  describe 'test an instance of ChargebackDefense' do
    it 'should create an instance of ChargebackDefense' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Komoju::ChargebackDefense)
    end
  end

  describe 'test attribute "product_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "shipping_info"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "recipient_info"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "documents"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
