=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Komoju::CreateSecureTokenRequestWithPaymentDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Komoju::CreateSecureTokenRequestWithPaymentDetails do
  #let(:instance) { Komoju::CreateSecureTokenRequestWithPaymentDetails.new }

  describe 'test an instance of CreateSecureTokenRequestWithPaymentDetails' do
    it 'should create an instance of CreateSecureTokenRequestWithPaymentDetails' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Komoju::CreateSecureTokenRequestWithPaymentDetails)
    end
  end

  describe 'test attribute "amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "currency"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "payment_details"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "return_url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "platform_details"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
