=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Komoju::Currency
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Komoju::Currency do
  #let(:instance) { Komoju::Currency.new }

  describe 'test an instance of Currency' do
    it 'should create an instance of Currency' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Komoju::Currency)
    end
  end

end
