=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Komoju::PrepaidCards
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Komoju::PrepaidCards do
  let(:instance) { Komoju::PrepaidCards.new }

  describe 'test an instance of PrepaidCards' do
    it 'should create an instance of PrepaidCards' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Komoju::PrepaidCards)
    end
  end

  describe 'test attribute "last_four_digits"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "points"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
