=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Komoju::SettlementDownload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Komoju::SettlementDownload do
  let(:instance) { Komoju::SettlementDownload.new }

  describe 'test an instance of SettlementDownload' do
    it 'should create an instance of SettlementDownload' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Komoju::SettlementDownload)
    end
  end

  describe 'test attribute "csv"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "xls"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
