=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Komoju
  class CreatePaymentRequest < ApiModelBase
    # Must be equal or greater than 0. Always in lowest denomination of the currency (e.g. cents for USD).
    attr_accessor :amount

    # If false, the payment will be authorized but not be captured. This option is ignored if a payment type is not credit_card.
    attr_accessor :capture

    # Plaintext description for annotating a resource.
    attr_accessor :description

    # Must be equal or greater than 0. Always in lowest denomination of the currency (e.g. cents for USD).
    attr_accessor :tax

    attr_accessor :currency

    # A unique ID from your application used to track this payment.
    attr_accessor :external_order_num

    attr_accessor :return_url

    attr_accessor :cancel_url

    attr_accessor :locale

    attr_accessor :partner_origin

    attr_accessor :metadata

    attr_accessor :payment_details

    attr_accessor :mcc

    attr_accessor :statement_descriptor

    attr_accessor :platform_details

    # The ID of an existing customer in which to provide payment details for the payment. This or payment_details must be present.
    attr_accessor :customer

    attr_accessor :fraud_details

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'amount' => :'amount',
        :'capture' => :'capture',
        :'description' => :'description',
        :'tax' => :'tax',
        :'currency' => :'currency',
        :'external_order_num' => :'external_order_num',
        :'return_url' => :'return_url',
        :'cancel_url' => :'cancel_url',
        :'locale' => :'locale',
        :'partner_origin' => :'partner_origin',
        :'metadata' => :'metadata',
        :'payment_details' => :'payment_details',
        :'mcc' => :'mcc',
        :'statement_descriptor' => :'statement_descriptor',
        :'platform_details' => :'platform_details',
        :'customer' => :'customer',
        :'fraud_details' => :'fraud_details'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'amount' => :'Integer',
        :'capture' => :'Boolean',
        :'description' => :'String',
        :'tax' => :'Integer',
        :'currency' => :'Currency',
        :'external_order_num' => :'String',
        :'return_url' => :'String',
        :'cancel_url' => :'String',
        :'locale' => :'Locale',
        :'partner_origin' => :'String',
        :'metadata' => :'String',
        :'payment_details' => :'PaymentDetailsAll',
        :'mcc' => :'String',
        :'statement_descriptor' => :'StatementDescriptor',
        :'platform_details' => :'PlatformDetails',
        :'customer' => :'String',
        :'fraud_details' => :'FraudDetails'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Komoju::CreatePaymentRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Komoju::CreatePaymentRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'capture')
        self.capture = attributes[:'capture']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'tax')
        self.tax = attributes[:'tax']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'external_order_num')
        self.external_order_num = attributes[:'external_order_num']
      end

      if attributes.key?(:'return_url')
        self.return_url = attributes[:'return_url']
      end

      if attributes.key?(:'cancel_url')
        self.cancel_url = attributes[:'cancel_url']
      end

      if attributes.key?(:'locale')
        self.locale = attributes[:'locale']
      end

      if attributes.key?(:'partner_origin')
        self.partner_origin = attributes[:'partner_origin']
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end

      if attributes.key?(:'payment_details')
        self.payment_details = attributes[:'payment_details']
      end

      if attributes.key?(:'mcc')
        self.mcc = attributes[:'mcc']
      end

      if attributes.key?(:'statement_descriptor')
        self.statement_descriptor = attributes[:'statement_descriptor']
      end

      if attributes.key?(:'platform_details')
        self.platform_details = attributes[:'platform_details']
      end

      if attributes.key?(:'customer')
        self.customer = attributes[:'customer']
      end

      if attributes.key?(:'fraud_details')
        self.fraud_details = attributes[:'fraud_details']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @amount.nil?
      return false if @currency.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      @currency = currency
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          amount == o.amount &&
          capture == o.capture &&
          description == o.description &&
          tax == o.tax &&
          currency == o.currency &&
          external_order_num == o.external_order_num &&
          return_url == o.return_url &&
          cancel_url == o.cancel_url &&
          locale == o.locale &&
          partner_origin == o.partner_origin &&
          metadata == o.metadata &&
          payment_details == o.payment_details &&
          mcc == o.mcc &&
          statement_descriptor == o.statement_descriptor &&
          platform_details == o.platform_details &&
          customer == o.customer &&
          fraud_details == o.fraud_details
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [amount, capture, description, tax, currency, external_order_num, return_url, cancel_url, locale, partner_origin, metadata, payment_details, mcc, statement_descriptor, platform_details, customer, fraud_details].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
