=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Komoju
  class PaymentDetailsPaidy < ApiModelBase
    attr_accessor :type

    attr_accessor :customer_age

    attr_accessor :customer_last_order_amount

    attr_accessor :customer_last_order_at

    attr_accessor :customer_lifetime_value

    attr_accessor :customer_name

    attr_accessor :customer_order_count

    attr_accessor :email

    attr_accessor :phone

    attr_accessor :external_customer_id

    attr_accessor :item_title

    attr_accessor :customer_name_kana

    attr_accessor :capture

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'customer_age' => :'customer_age',
        :'customer_last_order_amount' => :'customer_last_order_amount',
        :'customer_last_order_at' => :'customer_last_order_at',
        :'customer_lifetime_value' => :'customer_lifetime_value',
        :'customer_name' => :'customer_name',
        :'customer_order_count' => :'customer_order_count',
        :'email' => :'email',
        :'phone' => :'phone',
        :'external_customer_id' => :'external_customer_id',
        :'item_title' => :'item_title',
        :'customer_name_kana' => :'customer_name_kana',
        :'capture' => :'capture'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'String',
        :'customer_age' => :'Integer',
        :'customer_last_order_amount' => :'Integer',
        :'customer_last_order_at' => :'Integer',
        :'customer_lifetime_value' => :'Integer',
        :'customer_name' => :'String',
        :'customer_order_count' => :'Integer',
        :'email' => :'String',
        :'phone' => :'String',
        :'external_customer_id' => :'String',
        :'item_title' => :'String',
        :'customer_name_kana' => :'String',
        :'capture' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Komoju::PaymentDetailsPaidy` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Komoju::PaymentDetailsPaidy`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'customer_age')
        self.customer_age = attributes[:'customer_age']
      end

      if attributes.key?(:'customer_last_order_amount')
        self.customer_last_order_amount = attributes[:'customer_last_order_amount']
      end

      if attributes.key?(:'customer_last_order_at')
        self.customer_last_order_at = attributes[:'customer_last_order_at']
      end

      if attributes.key?(:'customer_lifetime_value')
        self.customer_lifetime_value = attributes[:'customer_lifetime_value']
      end

      if attributes.key?(:'customer_name')
        self.customer_name = attributes[:'customer_name']
      else
        self.customer_name = nil
      end

      if attributes.key?(:'customer_order_count')
        self.customer_order_count = attributes[:'customer_order_count']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.key?(:'external_customer_id')
        self.external_customer_id = attributes[:'external_customer_id']
      end

      if attributes.key?(:'item_title')
        self.item_title = attributes[:'item_title']
      end

      if attributes.key?(:'customer_name_kana')
        self.customer_name_kana = attributes[:'customer_name_kana']
      end

      if attributes.key?(:'capture')
        self.capture = attributes[:'capture']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @customer_name.nil?
        invalid_properties.push('invalid value for "customer_name", customer_name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["paidy"])
      return false unless type_validator.valid?(@type)
      return false if @customer_name.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["paidy"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_name Value to be assigned
    def customer_name=(customer_name)
      if customer_name.nil?
        fail ArgumentError, 'customer_name cannot be nil'
      end

      @customer_name = customer_name
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          customer_age == o.customer_age &&
          customer_last_order_amount == o.customer_last_order_amount &&
          customer_last_order_at == o.customer_last_order_at &&
          customer_lifetime_value == o.customer_lifetime_value &&
          customer_name == o.customer_name &&
          customer_order_count == o.customer_order_count &&
          email == o.email &&
          phone == o.phone &&
          external_customer_id == o.external_customer_id &&
          item_title == o.item_title &&
          customer_name_kana == o.customer_name_kana &&
          capture == o.capture
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, customer_age, customer_last_order_amount, customer_last_order_at, customer_lifetime_value, customer_name, customer_order_count, email, phone, external_customer_id, item_title, customer_name_kana, capture].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
