=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Komoju
  module CreateSessionRequest
    class << self
      # List of class defined in oneOf (OpenAPI v3)
      def openapi_one_of
        [
          :'CreateSessionRequestWithCustomerMode',
          :'CreateSessionRequestWithCustomerPaymentMode',
          :'CreateSessionRequestWithPaymentMode'
        ]
      end

      # Discriminator's property name (OpenAPI v3)
      def openapi_discriminator_name
        :'mode'
      end

      # Discriminator's mapping (OpenAPI v3)
      def openapi_discriminator_mapping
        {
          :'customer' => :'CreateSessionRequestWithCustomerMode',
          :'customer_payment' => :'CreateSessionRequestWithCustomerPaymentMode',
          :'payment' => :'CreateSessionRequestWithPaymentMode'
        }
      end

      # Builds the object
      # @param [Mixed] Data to be matched against the list of oneOf items
      # @return [Object] Returns the model or the data itself
      def build(data)
        discriminator_value = data[openapi_discriminator_name]
        return nil if discriminator_value.nil?

        klass = openapi_discriminator_mapping[discriminator_value.to_s.to_sym]
        return nil unless klass

        Komoju.const_get(klass).build_from_hash(data)
      end
    end
  end

end
