=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Komoju
  # Specify customer's personal information to help us determine the legitimacy of the payment. It's recommended to include this information whenever possible to reduce the number of chargebacks.  See [Fraud Details](https://doc.komoju.com/docs/fraud-details) for more details.
  class FraudDetails < ApiModelBase
    # IPv4 or IPv6-formatted IP address of the customer at the time of payment.
    attr_accessor :customer_ip

    # Customer's email address.  This field can be omitted if `email` is provided in `email` field inside `payment_details` of create payment request, or in the create payment session request. Otherwise, this field is required.
    attr_accessor :customer_email

    # An unique identifier of your customer. If your system has the concept of user accounts, then the ID of the current logged in user would be appropriate.
    attr_accessor :customer_id

    # Customer's current language setting.
    attr_accessor :browser_language

    # Browser's [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) string.
    attr_accessor :browser_user_agent

    # A unique identifier for the current browser session. We expect this to behave similarly to the lifetime of [window.sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) in a web browsing context.
    attr_accessor :browser_session_id

    # Customer's phone number.
    attr_accessor :phone

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'customer_ip' => :'customer_ip',
        :'customer_email' => :'customer_email',
        :'customer_id' => :'customer_id',
        :'browser_language' => :'browser_language',
        :'browser_user_agent' => :'browser_user_agent',
        :'browser_session_id' => :'browser_session_id',
        :'phone' => :'phone'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'customer_ip' => :'String',
        :'customer_email' => :'String',
        :'customer_id' => :'String',
        :'browser_language' => :'String',
        :'browser_user_agent' => :'String',
        :'browser_session_id' => :'String',
        :'phone' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Komoju::FraudDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Komoju::FraudDetails`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'customer_ip')
        self.customer_ip = attributes[:'customer_ip']
      else
        self.customer_ip = nil
      end

      if attributes.key?(:'customer_email')
        self.customer_email = attributes[:'customer_email']
      else
        self.customer_email = nil
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'browser_language')
        self.browser_language = attributes[:'browser_language']
      end

      if attributes.key?(:'browser_user_agent')
        self.browser_user_agent = attributes[:'browser_user_agent']
      end

      if attributes.key?(:'browser_session_id')
        self.browser_session_id = attributes[:'browser_session_id']
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @customer_ip.nil?
        invalid_properties.push('invalid value for "customer_ip", customer_ip cannot be nil.')
      end

      if @customer_email.nil?
        invalid_properties.push('invalid value for "customer_email", customer_email cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @customer_ip.nil?
      return false if @customer_email.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_ip Value to be assigned
    def customer_ip=(customer_ip)
      if customer_ip.nil?
        fail ArgumentError, 'customer_ip cannot be nil'
      end

      @customer_ip = customer_ip
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_email Value to be assigned
    def customer_email=(customer_email)
      if customer_email.nil?
        fail ArgumentError, 'customer_email cannot be nil'
      end

      @customer_email = customer_email
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          customer_ip == o.customer_ip &&
          customer_email == o.customer_email &&
          customer_id == o.customer_id &&
          browser_language == o.browser_language &&
          browser_user_agent == o.browser_user_agent &&
          browser_session_id == o.browser_session_id &&
          phone == o.phone
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [customer_ip, customer_email, customer_id, browser_language, browser_user_agent, browser_session_id, phone].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
