=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Komoju
  class Submerchant < ApiModelBase
    # A unique 25-character alphanumeric merchant identifier.
    attr_accessor :submerchant_id

    # The amount with tax included, greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
    attr_accessor :amount

    # The platform fee amount, tax included, greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
    attr_accessor :platform_fee

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'submerchant_id' => :'submerchant_id',
        :'amount' => :'amount',
        :'platform_fee' => :'platform_fee'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'submerchant_id' => :'String',
        :'amount' => :'Integer',
        :'platform_fee' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Komoju::Submerchant` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Komoju::Submerchant`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'submerchant_id')
        self.submerchant_id = attributes[:'submerchant_id']
      else
        self.submerchant_id = nil
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'platform_fee')
        self.platform_fee = attributes[:'platform_fee']
      else
        self.platform_fee = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @submerchant_id.nil?
        invalid_properties.push('invalid value for "submerchant_id", submerchant_id cannot be nil.')
      end

      if @submerchant_id.to_s.length > 25
        invalid_properties.push('invalid value for "submerchant_id", the character length must be smaller than or equal to 25.')
      end

      if @submerchant_id.to_s.length < 25
        invalid_properties.push('invalid value for "submerchant_id", the character length must be greater than or equal to 25.')
      end

      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @amount < 0
        invalid_properties.push('invalid value for "amount", must be greater than or equal to 0.')
      end

      if @platform_fee.nil?
        invalid_properties.push('invalid value for "platform_fee", platform_fee cannot be nil.')
      end

      if @platform_fee < 0
        invalid_properties.push('invalid value for "platform_fee", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @submerchant_id.nil?
      return false if @submerchant_id.to_s.length > 25
      return false if @submerchant_id.to_s.length < 25
      return false if @amount.nil?
      return false if @amount < 0
      return false if @platform_fee.nil?
      return false if @platform_fee < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] submerchant_id Value to be assigned
    def submerchant_id=(submerchant_id)
      if submerchant_id.nil?
        fail ArgumentError, 'submerchant_id cannot be nil'
      end

      if submerchant_id.to_s.length > 25
        fail ArgumentError, 'invalid value for "submerchant_id", the character length must be smaller than or equal to 25.'
      end

      if submerchant_id.to_s.length < 25
        fail ArgumentError, 'invalid value for "submerchant_id", the character length must be greater than or equal to 25.'
      end

      @submerchant_id = submerchant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      if amount < 0
        fail ArgumentError, 'invalid value for "amount", must be greater than or equal to 0.'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] platform_fee Value to be assigned
    def platform_fee=(platform_fee)
      if platform_fee.nil?
        fail ArgumentError, 'platform_fee cannot be nil'
      end

      if platform_fee < 0
        fail ArgumentError, 'invalid value for "platform_fee", must be greater than or equal to 0.'
      end

      @platform_fee = platform_fee
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          submerchant_id == o.submerchant_id &&
          amount == o.amount &&
          platform_fee == o.platform_fee
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [submerchant_id, amount, platform_fee].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
