=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Komoju
  class Subscription < ApiModelBase
    # A unique 25-character alphanumeric resource identifier.
    attr_accessor :id

    attr_accessor :resource

    attr_accessor :status

    # Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
    attr_accessor :amount

    attr_accessor :currency

    attr_accessor :customer

    attr_accessor :period

    attr_accessor :day

    attr_accessor :payment_details

    attr_accessor :retry_count

    attr_accessor :retry_at

    attr_accessor :next_capture_at

    attr_accessor :created_at

    attr_accessor :ended_at

    attr_accessor :metadata

    attr_accessor :payments

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'resource' => :'resource',
        :'status' => :'status',
        :'amount' => :'amount',
        :'currency' => :'currency',
        :'customer' => :'customer',
        :'period' => :'period',
        :'day' => :'day',
        :'payment_details' => :'payment_details',
        :'retry_count' => :'retry_count',
        :'retry_at' => :'retry_at',
        :'next_capture_at' => :'next_capture_at',
        :'created_at' => :'created_at',
        :'ended_at' => :'ended_at',
        :'metadata' => :'metadata',
        :'payments' => :'payments'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'resource' => :'String',
        :'status' => :'String',
        :'amount' => :'Integer',
        :'currency' => :'Currency',
        :'customer' => :'SubscriptionCustomer',
        :'period' => :'SubscriptionPeriod',
        :'day' => :'Integer',
        :'payment_details' => :'SubscriptionPaymentDetails',
        :'retry_count' => :'Integer',
        :'retry_at' => :'Time',
        :'next_capture_at' => :'Time',
        :'created_at' => :'Time',
        :'ended_at' => :'Time',
        :'metadata' => :'Object',
        :'payments' => :'Array<Object>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Komoju::Subscription` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Komoju::Subscription`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'resource')
        self.resource = attributes[:'resource']
      else
        self.resource = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'customer')
        self.customer = attributes[:'customer']
      else
        self.customer = nil
      end

      if attributes.key?(:'period')
        self.period = attributes[:'period']
      else
        self.period = nil
      end

      if attributes.key?(:'day')
        self.day = attributes[:'day']
      else
        self.day = nil
      end

      if attributes.key?(:'payment_details')
        self.payment_details = attributes[:'payment_details']
      else
        self.payment_details = nil
      end

      if attributes.key?(:'retry_count')
        self.retry_count = attributes[:'retry_count']
      else
        self.retry_count = nil
      end

      if attributes.key?(:'retry_at')
        self.retry_at = attributes[:'retry_at']
      else
        self.retry_at = nil
      end

      if attributes.key?(:'next_capture_at')
        self.next_capture_at = attributes[:'next_capture_at']
      else
        self.next_capture_at = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'ended_at')
        self.ended_at = attributes[:'ended_at']
      else
        self.ended_at = nil
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      else
        self.metadata = nil
      end

      if attributes.key?(:'payments')
        if (value = attributes[:'payments']).is_a?(Array)
          self.payments = value
        end
      else
        self.payments = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @id.to_s.length > 25
        invalid_properties.push('invalid value for "id", the character length must be smaller than or equal to 25.')
      end

      if @id.to_s.length < 25
        invalid_properties.push('invalid value for "id", the character length must be greater than or equal to 25.')
      end

      if @resource.nil?
        invalid_properties.push('invalid value for "resource", resource cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @amount < 0
        invalid_properties.push('invalid value for "amount", must be greater than or equal to 0.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @customer.nil?
        invalid_properties.push('invalid value for "customer", customer cannot be nil.')
      end

      if @period.nil?
        invalid_properties.push('invalid value for "period", period cannot be nil.')
      end

      if @day.nil?
        invalid_properties.push('invalid value for "day", day cannot be nil.')
      end

      if @payment_details.nil?
        invalid_properties.push('invalid value for "payment_details", payment_details cannot be nil.')
      end

      if @retry_count.nil?
        invalid_properties.push('invalid value for "retry_count", retry_count cannot be nil.')
      end

      if @retry_at.nil?
        invalid_properties.push('invalid value for "retry_at", retry_at cannot be nil.')
      end

      if @next_capture_at.nil?
        invalid_properties.push('invalid value for "next_capture_at", next_capture_at cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @ended_at.nil?
        invalid_properties.push('invalid value for "ended_at", ended_at cannot be nil.')
      end

      if @metadata.nil?
        invalid_properties.push('invalid value for "metadata", metadata cannot be nil.')
      end

      if @payments.nil?
        invalid_properties.push('invalid value for "payments", payments cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @id.to_s.length > 25
      return false if @id.to_s.length < 25
      return false if @resource.nil?
      return false if @status.nil?
      return false if @amount.nil?
      return false if @amount < 0
      return false if @currency.nil?
      return false if @customer.nil?
      return false if @period.nil?
      return false if @day.nil?
      return false if @payment_details.nil?
      return false if @retry_count.nil?
      return false if @retry_at.nil?
      return false if @next_capture_at.nil?
      return false if @created_at.nil?
      return false if @ended_at.nil?
      return false if @metadata.nil?
      return false if @payments.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      if id.to_s.length > 25
        fail ArgumentError, 'invalid value for "id", the character length must be smaller than or equal to 25.'
      end

      if id.to_s.length < 25
        fail ArgumentError, 'invalid value for "id", the character length must be greater than or equal to 25.'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] resource Value to be assigned
    def resource=(resource)
      if resource.nil?
        fail ArgumentError, 'resource cannot be nil'
      end

      @resource = resource
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      if amount < 0
        fail ArgumentError, 'invalid value for "amount", must be greater than or equal to 0.'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] customer Value to be assigned
    def customer=(customer)
      if customer.nil?
        fail ArgumentError, 'customer cannot be nil'
      end

      @customer = customer
    end

    # Custom attribute writer method with validation
    # @param [Object] period Value to be assigned
    def period=(period)
      if period.nil?
        fail ArgumentError, 'period cannot be nil'
      end

      @period = period
    end

    # Custom attribute writer method with validation
    # @param [Object] day Value to be assigned
    def day=(day)
      if day.nil?
        fail ArgumentError, 'day cannot be nil'
      end

      @day = day
    end

    # Custom attribute writer method with validation
    # @param [Object] payment_details Value to be assigned
    def payment_details=(payment_details)
      if payment_details.nil?
        fail ArgumentError, 'payment_details cannot be nil'
      end

      @payment_details = payment_details
    end

    # Custom attribute writer method with validation
    # @param [Object] retry_count Value to be assigned
    def retry_count=(retry_count)
      if retry_count.nil?
        fail ArgumentError, 'retry_count cannot be nil'
      end

      @retry_count = retry_count
    end

    # Custom attribute writer method with validation
    # @param [Object] retry_at Value to be assigned
    def retry_at=(retry_at)
      if retry_at.nil?
        fail ArgumentError, 'retry_at cannot be nil'
      end

      @retry_at = retry_at
    end

    # Custom attribute writer method with validation
    # @param [Object] next_capture_at Value to be assigned
    def next_capture_at=(next_capture_at)
      if next_capture_at.nil?
        fail ArgumentError, 'next_capture_at cannot be nil'
      end

      @next_capture_at = next_capture_at
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] ended_at Value to be assigned
    def ended_at=(ended_at)
      if ended_at.nil?
        fail ArgumentError, 'ended_at cannot be nil'
      end

      @ended_at = ended_at
    end

    # Custom attribute writer method with validation
    # @param [Object] metadata Value to be assigned
    def metadata=(metadata)
      if metadata.nil?
        fail ArgumentError, 'metadata cannot be nil'
      end

      @metadata = metadata
    end

    # Custom attribute writer method with validation
    # @param [Object] payments Value to be assigned
    def payments=(payments)
      if payments.nil?
        fail ArgumentError, 'payments cannot be nil'
      end

      @payments = payments
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          resource == o.resource &&
          status == o.status &&
          amount == o.amount &&
          currency == o.currency &&
          customer == o.customer &&
          period == o.period &&
          day == o.day &&
          payment_details == o.payment_details &&
          retry_count == o.retry_count &&
          retry_at == o.retry_at &&
          next_capture_at == o.next_capture_at &&
          created_at == o.created_at &&
          ended_at == o.ended_at &&
          metadata == o.metadata &&
          payments == o.payments
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, resource, status, amount, currency, customer, period, day, payment_details, retry_count, retry_at, next_capture_at, created_at, ended_at, metadata, payments].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
