=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module Komoju
  class TokenPaymentDetails < ApiModelBase
    attr_accessor :type

    attr_accessor :email

    attr_accessor :phone

    attr_accessor :given_name

    attr_accessor :family_name

    attr_accessor :given_name_kana

    attr_accessor :family_name_kana

    attr_accessor :store

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'email' => :'email',
        :'phone' => :'phone',
        :'given_name' => :'given_name',
        :'family_name' => :'family_name',
        :'given_name_kana' => :'given_name_kana',
        :'family_name_kana' => :'family_name_kana',
        :'store' => :'store'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'String',
        :'email' => :'String',
        :'phone' => :'String',
        :'given_name' => :'String',
        :'family_name' => :'String',
        :'given_name_kana' => :'String',
        :'family_name_kana' => :'String',
        :'store' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Komoju::TokenPaymentDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Komoju::TokenPaymentDetails`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      else
        self.phone = nil
      end

      if attributes.key?(:'given_name')
        self.given_name = attributes[:'given_name']
      else
        self.given_name = nil
      end

      if attributes.key?(:'family_name')
        self.family_name = attributes[:'family_name']
      else
        self.family_name = nil
      end

      if attributes.key?(:'given_name_kana')
        self.given_name_kana = attributes[:'given_name_kana']
      else
        self.given_name_kana = nil
      end

      if attributes.key?(:'family_name_kana')
        self.family_name_kana = attributes[:'family_name_kana']
      else
        self.family_name_kana = nil
      end

      if attributes.key?(:'store')
        self.store = attributes[:'store']
      else
        self.store = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @phone.nil?
        invalid_properties.push('invalid value for "phone", phone cannot be nil.')
      end

      if @given_name.nil?
        invalid_properties.push('invalid value for "given_name", given_name cannot be nil.')
      end

      if @family_name.nil?
        invalid_properties.push('invalid value for "family_name", family_name cannot be nil.')
      end

      if @given_name_kana.nil?
        invalid_properties.push('invalid value for "given_name_kana", given_name_kana cannot be nil.')
      end

      if @family_name_kana.nil?
        invalid_properties.push('invalid value for "family_name_kana", family_name_kana cannot be nil.')
      end

      if @store.nil?
        invalid_properties.push('invalid value for "store", store cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type.nil?
      return false if @email.nil?
      return false if @phone.nil?
      return false if @given_name.nil?
      return false if @family_name.nil?
      return false if @given_name_kana.nil?
      return false if @family_name_kana.nil?
      return false if @store.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      if type.nil?
        fail ArgumentError, 'type cannot be nil'
      end

      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.nil?
        fail ArgumentError, 'email cannot be nil'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] phone Value to be assigned
    def phone=(phone)
      if phone.nil?
        fail ArgumentError, 'phone cannot be nil'
      end

      @phone = phone
    end

    # Custom attribute writer method with validation
    # @param [Object] given_name Value to be assigned
    def given_name=(given_name)
      if given_name.nil?
        fail ArgumentError, 'given_name cannot be nil'
      end

      @given_name = given_name
    end

    # Custom attribute writer method with validation
    # @param [Object] family_name Value to be assigned
    def family_name=(family_name)
      if family_name.nil?
        fail ArgumentError, 'family_name cannot be nil'
      end

      @family_name = family_name
    end

    # Custom attribute writer method with validation
    # @param [Object] given_name_kana Value to be assigned
    def given_name_kana=(given_name_kana)
      if given_name_kana.nil?
        fail ArgumentError, 'given_name_kana cannot be nil'
      end

      @given_name_kana = given_name_kana
    end

    # Custom attribute writer method with validation
    # @param [Object] family_name_kana Value to be assigned
    def family_name_kana=(family_name_kana)
      if family_name_kana.nil?
        fail ArgumentError, 'family_name_kana cannot be nil'
      end

      @family_name_kana = family_name_kana
    end

    # Custom attribute writer method with validation
    # @param [Object] store Value to be assigned
    def store=(store)
      if store.nil?
        fail ArgumentError, 'store cannot be nil'
      end

      @store = store
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          email == o.email &&
          phone == o.phone &&
          given_name == o.given_name &&
          family_name == o.family_name &&
          given_name_kana == o.given_name_kana &&
          family_name_kana == o.family_name_kana &&
          store == o.store
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, email, phone, given_name, family_name, given_name_kana, family_name_kana, store].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
