=begin
#KOMOJU API

#Full featured access to the KOMOJU payments system.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'cgi'

module Komoju
  class TokensApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Token: Create
    # Creates a token with the given `payment_details`.  It is recommended to have a client application make this request directly so that sensitive payment information (e.g. credit card number) doesn't hit your server. Receiving credit card numbers requires your business to be PCI-DSS compliant. Once you turn your customer's details into a token, the token string can safely be sent to your server and used as `payment_details` to a future KOMOJU API request.  A `currency` may be optionally specified. When `currency` is provided, KOMOJU will ensure that the payment made using the new token is in the same currency.
    # @param create_token_request [CreateTokenRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Token]
    def create_token(create_token_request, opts = {})
      data, _status_code, _headers = create_token_with_http_info(create_token_request, opts)
      data
    end

    # Token: Create
    # Creates a token with the given &#x60;payment_details&#x60;.  It is recommended to have a client application make this request directly so that sensitive payment information (e.g. credit card number) doesn&#39;t hit your server. Receiving credit card numbers requires your business to be PCI-DSS compliant. Once you turn your customer&#39;s details into a token, the token string can safely be sent to your server and used as &#x60;payment_details&#x60; to a future KOMOJU API request.  A &#x60;currency&#x60; may be optionally specified. When &#x60;currency&#x60; is provided, KOMOJU will ensure that the payment made using the new token is in the same currency.
    # @param create_token_request [CreateTokenRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Token, Integer, Hash)>] Token data, response status code and response headers
    def create_token_with_http_info(create_token_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TokensApi.create_token ...'
      end
      # verify the required parameter 'create_token_request' is set
      if @api_client.config.client_side_validation && create_token_request.nil?
        fail ArgumentError, "Missing the required parameter 'create_token_request' when calling TokensApi.create_token"
      end
      # resource path
      local_var_path = '/tokens'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(create_token_request)

      # return_type
      return_type = opts[:debug_return_type] || 'Token'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['api_key']

      new_options = opts.merge(
        :operation => :"TokensApi.create_token",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TokensApi#create_token\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
