name: Validate

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate:
    runs-on: [self-hosted, beta, public-release]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: '3.2'
      - name: Build gem
        run: gem build komoju-sdk.gemspec